version: '3.8'
services:
    scrapy:
        build: .
        volumes:
            - .:/app/
        depends_on:
            - database
        command: ['sleep', 'infinity']
    database:
        image: mongo:5.0.2-focal
        volumes:
            - dbdata:/data/db
        expose:
            - 27017
volumes:
    dbdata:
